In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [3]:
#2D 5x5 of random integers
array1 = np.random.randint(0,101,size=(5,5))

In [4]:
#reshaping the created array to 1D array
array2 = array1.flatten()
array2


array([85, 44, 89, 65, 32, 43, 76, 77, 44, 28, 48, 88, 99, 41, 52, 93,  7,
       52, 59,  5, 75, 78, 62, 78, 69])

In [5]:
#calculating the cumulatinve sum along the rows of the reshaped array
cumulativeSum = np.cumsum(array2)
print(cumulativeSum)

[  85  129  218  283  315  358  434  511  555  583  631  719  818  859
  911 1004 1011 1063 1122 1127 1202 1280 1342 1420 1489]


In [12]:
#a function that takes two arrays as input and returns the intersection
def intersection(a,b):
    return np.intersect1d(a,b)

n= int(input('Enter number of elements: '))
arr1 = list(map(int, 
    input("\nEnter the numbers : ").strip().split()))[:n]

n= int(input('Enter number of elements: '))
arr2 = list(map(int,input('\nEnter numbers: ').strip().split()))[:n]

print(intersection(np.array(arr1),np.array(arr2)))


[2]


In [14]:
#implementing softmax function
softmax = np.exp(array2)/sum(np.exp(array2))
print(softmax)


[8.29420591e-07 1.29628667e-24 4.52848299e-05 1.70956326e-15
 7.96466057e-30 4.76877216e-25 1.02358633e-10 2.78239611e-10
 1.29628667e-24 1.45877847e-31 7.07748541e-23 1.66593579e-05
 9.97464757e-01 6.45383130e-26 3.86417610e-21 2.47246794e-03
 1.10612759e-40 3.86417610e-21 4.23758364e-18 1.49698091e-41
 3.76556366e-11 7.56333679e-10 8.51141427e-17 7.56333679e-10
 9.33389912e-14]


In [21]:
#creating a matrix with random integers and replace negative integers with their abs square
array3 = np.random.randint(-20,20,size=(15))
print(array3)
arr3 = [x*x if x < 0 else x for x in array3]
print(arr3)

[ 16  -3 -17  13 -18  19  18  13   6   8   9  17 -18   5 -14]
[16, 9, 289, 13, 324, 19, 18, 13, 6, 8, 9, 17, 324, 5, 196]


In [29]:
array4 = np.random.randint(0,100,size=(6,6))
symmetricArray = (array4+array4.T)/2
print(symmetricArray)

eigenVal = np.linalg.eig(symmetricArray)
print(eigenVal)


[[25.  83.  61.  75.  27.  42.5]
 [83.  67.  26.  52.  50.  36. ]
 [61.  26.  32.  47.  39.5 11.5]
 [75.  52.  47.  99.  36.5 75. ]
 [27.  50.  39.5 36.5 63.  72. ]
 [42.5 36.  11.5 75.  72.  85. ]]
EigResult(eigenvalues=array([315.17486845, -62.80850764, -19.32844574,  70.14649819,
        23.01521007,  44.80037667]), eigenvectors=array([[-0.40674191, -0.74618613, -0.35747343, -0.38087961,  0.06672802,
        -0.02140385],
       [-0.41008601,  0.41627601,  0.0895258 , -0.33629963,  0.56583395,
        -0.4661152 ],
       [-0.27943384,  0.4158835 , -0.32337248, -0.33516754, -0.72470611,
        -0.0827747 ],
       [-0.51360362,  0.0703166 ,  0.51337428, -0.11181552, -0.01601234,
         0.67450325],
       [-0.36729506, -0.25249129,  0.45820767,  0.4269677 , -0.3435798 ,
        -0.53948098],
       [-0.4354456 ,  0.16812254, -0.53490251,  0.65931166,  0.17854102,
         0.17155898]]))


In [30]:
#calculating moving average of 1D array
import numpy as np

def moving_average(arr, window_size):
    if window_size <= 0 or window_size > len(arr):
        raise ValueError("Window size must be a positive integer less than or equal to the length of the array.")
    
    moving_averages = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
    return moving_averages


array5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window = 3
result = moving_average(array5, window)
print("Moving averages:", result)


Moving averages: [2. 3. 4. 5. 6. 7. 8. 9.]


In [50]:
#checkerboard pattern using zeros and ones
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
#pearson correlation coefficient of two random arrays of same length

array5 = np.random.randint(1,20,size=(3,3))
array6 = np.random.randint(1,30,size=(3,3))

print(np.corrcoef(array5,array6))

[[ 1.         -0.55541867 -0.3592106   0.97893383 -0.39828092 -0.256683  ]
 [-0.55541867  1.         -0.57655666 -0.37392985 -0.54155693 -0.66114309]
 [-0.3592106  -0.57655666  1.         -0.54219364  0.99910887  0.99419163]
 [ 0.97893383 -0.37392985 -0.54219364  1.         -0.57717547 -0.44861259]
 [-0.39828092 -0.54155693  0.99910887 -0.57717547  1.          0.98876311]
 [-0.256683   -0.66114309  0.99419163 -0.44861259  0.98876311  1.        ]]


In [65]:
#Generate a random 3D array and compute the sum along each axis

array3d = np.random.randint(1,100, size=(2,3,4))

print(f'axis-1: {np.sum(array3d,axis=0)}\n\naxis-2:{np.sum(array3d,axis=1)}\n\n axis-3:{np.sum(array3d,axis=2)}\n' )

axis-1: [[ 79 138  14  34]
 [ 41 131 172  78]
 [ 55 138 141 161]]

axis-2:[[ 98 180 169 162]
 [ 77 227 158 111]]

 axis-3:[[154 166 289]
 [111 256 206]]



## Pandas

In [71]:
#Read multiple CSV files from a directory into a single pandas DataFrame and concatenate them.

df = pd.concat(map(pd.read_csv, ['train.csv', 'test.csv']))

In [72]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       1.0       1   
2            3       1.0       3   
3            4       1.0       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [83]:
specificAge = df[(df['Age']>= 25) & (df['Age']<=35)]
print(specificAge.head())
print(specificAge.count())

    PassengerId  Survived  Pclass  \
2             3       1.0       3   
3             4       1.0       1   
4             5       0.0       3   
8             9       1.0       3   
18           19       0.0       3   

                                                 Name     Sex   Age  SibSp  \
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   

    Parch            Ticket     Fare Cabin Embarked  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
8       2            347742  11.1333   NaN        S  
18      0            345763  18.0000  

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64  
 3   Name         1309 non-null   object 
 4   Sex          1309 non-null   object 
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64  
 7   Parch        1309 non-null   int64  
 8   Ticket       1309 non-null   object 
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object 
 11  Embarked     1307 non-null   object 
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB


In [85]:
df_store = pd.read_csv('Global_Superstore(CSV).csv')

In [87]:
df_store.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')