In [2]:
import numpy as np
import pandas as pd

In [18]:
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))

In [21]:
print(arr1)
print(arr2)

[[8 7 7]
 [6 8 8]
 [0 8 1]]
[[0 5 8]
 [9 2 8]
 [9 9 5]]


In [19]:
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 8 12 15]
 [15 10 16]
 [ 9 17  6]]
[[ 8 12 15]
 [15 10 16]
 [ 9 17  6]]


In [20]:
print(np.dot(arr1,arr2))
print(np.multiply(arr1,arr2))

[[126 117 155]
 [144 118 152]
 [ 81  25  69]]
[[ 0 35 56]
 [54 16 64]
 [ 0 72  5]]
[[ 0 35 56]
 [54 16 64]
 [ 0 72  5]]


In [27]:
print(arr1/arr2)
print(np.mod(arr1,arr2))

[[       inf 1.4        0.875     ]
 [0.66666667 4.         1.        ]
 [0.         0.88888889 0.2       ]]
[[0 2 7]
 [6 0 0]
 [0 8 1]]


C:\Users\Anitha\AppData\Local\Temp\ipykernel_4868\522110001.py:1: RuntimeWarning: divide by zero encountered in divide
  print(arr1/arr2)
C:\Users\Anitha\AppData\Local\Temp\ipykernel_4868\522110001.py:2: RuntimeWarning: divide by zero encountered in remainder
  print(np.mod(arr1,arr2))
