In [2]:
import numpy as np
import pandas as pd

## Array Operations


In [11]:
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))
print(arr1)
print(arr2)

[[8 2 5]
 [8 4 6]
 [5 4 2]]
[[4 8 5]
 [2 8 6]
 [3 8 5]]


In [12]:
print(arr1+arr2)
print(np.add(arr1,arr2))

[[12 10 10]
 [10 12 12]
 [ 8 12  7]]
[[12 10 10]
 [10 12 12]
 [ 8 12  7]]


In [15]:
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ 4 -6  0]
 [ 6 -4  0]
 [ 2 -4 -3]]
[[ 4 -6  0]
 [ 6 -4  0]
 [ 2 -4 -3]]


In [13]:
print(np.dot(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 51 120  77]
 [ 58 144  94]
 [ 34  88  59]]
[[32 16 25]
 [16 32 36]
 [15 32 10]]


In [14]:
print(np.mod(arr1,arr2))

[[0 2 0]
 [0 4 0]
 [2 4 2]]


## Statistical Analysis

In [26]:
array = np.array(np.random.randint(10,size=20))
print(array)

[2 1 8 6 8 1 7 9 6 1 0 6 3 5 3 8 6 6 0 8]


In [31]:
print(f'Median of array = {np.median(array)}')
print(f'Mean of array = {np.mean(array)}')
print(f'Standard deviation of array = {np.std(array)}')
print(f'Variance of array = {np.var(array)}')

Median of array = 6.0
Mean of array = 4.7
Standard deviation of array = 2.951270912674741
Variance of array = 8.709999999999999


## Matrix Manipulation