Name: Dheephiga A M

Temp ID: WDGET2024067

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

## Array Operations


In [2]:
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))
print(arr1)
print(arr2)

[[2 4 7]
 [4 0 7]
 [0 8 4]]
[[2 3 8]
 [1 2 2]
 [0 2 0]]


### Addition

In [3]:
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 4  7 15]
 [ 5  2  9]
 [ 0 10  4]]
[[ 4  7 15]
 [ 5  2  9]
 [ 0 10  4]]


### Subtraction

In [4]:
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ 0  1 -1]
 [ 3 -2  5]
 [ 0  6  4]]
[[ 0  1 -1]
 [ 3 -2  5]
 [ 0  6  4]]


### Multiplication & Dot Product

In [5]:
print(np.dot(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 8 28 24]
 [ 8 26 32]
 [ 8 24 16]]
[[ 4 12 56]
 [ 4  0 14]
 [ 0 16  0]]


### Division

In [6]:
print(np.mod(arr1,arr2))

[[0 1 7]
 [0 0 1]
 [0 0 0]]


C:\Users\Anitha\AppData\Local\Temp\ipykernel_9396\3538559506.py:1: RuntimeWarning: divide by zero encountered in remainder
  print(np.mod(arr1,arr2))


## Statistical Analysis

In [7]:
array = np.array(np.random.randint(10,size=20))
print(array)

[3 2 5 2 1 5 3 2 1 5 5 6 6 0 8 1 7 1 5 7]


In [8]:
print(f'Median of array = {np.median(array)}')
print(f'Mean of array = {np.mean(array)}')
print(f'Standard deviation of array = {np.std(array)}')
print(f'Variance of array = {np.var(array)}')

Median of array = 4.0
Mean of array = 3.75
Standard deviation of array = 2.3637893307145625
Variance of array = 5.5875


## Matrix Manipulation

In [9]:
matrix = np.random.randint(low=1,high=30,size=(3,3))
print(matrix)

[[ 9 24 16]
 [ 3 10  6]
 [28 21 19]]


In [10]:
#matrix transposition
print(f'transposed matrix:\n {np.transpose(matrix)}')

#matrix dot product
print(f'dot product of the matrix: \n {np.dot(matrix,matrix)}')

#matrix determinant
print(f'Determinant of the matrix: \n{np.linalg.det(matrix)}')

transposed matrix:
 [[ 9  3 28]
 [24 10 21]
 [16  6 19]]
dot product of the matrix: 
 [[ 601  792  592]
 [ 225  298  222]
 [ 847 1281  935]]
Determinant of the matrix: 
-231.99999999999977


## Data Exploaration and Analysis

In [11]:
data = pd.read_csv('titanic.csv')
print(data.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [12]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [14]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [15]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
avg_age = data['Age'].mean()
data['Age'] = data['Age'].replace(np.nan,avg_age)

In [17]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [18]:
data['Cabin'].isna().sum()


687

In [19]:
data = data.drop(['Cabin'],axis=1)

In [20]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [21]:
data['Embarked']= data["Embarked"].replace(np.nan,'Q')

In [22]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [23]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [24]:
grp = data.groupby('Sex')
grp.first()
grp.get_group('male')

PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

           Age  SibSp  Parch            Ticket     Fare Embarked  
0    22.000000      1      0         A/5 21171   7.2500        S  
4    35.000000      0      0            373450   8.0500        S  
5    29.699118      0      0            330877   8.4583        Q  
6    54.000000      0      0             17463  51.8625        S  
7     2.000000      3      1            349909  21.0750        S  
..         ...    ...    ...               ...      ...      ...  
883  28.000000      0      0  C.A./SOTON 34068  10.5000        S  
884  25.000000      0      0   SOTON/OQ 392076   7.0500        S  
886  27.000000      0      0            211536  13.0000        S  
889  26.000000      0      0            111369  30.0000        C  
890  32.000000      0      0            370376   7.7500        Q  

[577 rows x 11 columns]

In [25]:
data['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [26]:
data['Embarked'].value_counts()

Embarked
S    644
C    168
Q     79
Name: count, dtype: int64

In [27]:
dfTable = data[['Sex','Survived','Embarked']]
table = pd.pivot_table(dfTable, index='Sex',columns='Survived',aggfunc='count')
print(table)

         Embarked     
Survived        0    1
Sex                   
female         81  233
male          468  109


In [28]:
dfTable = data[['Sex','Survived','Embarked']]
table = pd.pivot_table(dfTable, index='Sex',columns='Embarked',aggfunc='count')
print(table)

         Survived         
Embarked        C   Q    S
Sex                       
female         73  38  203
male           95  41  441


## Data Manipulation and Transformation

In [29]:
data['avgFare'] = np.array(data['Fare']).mean()
print(data['avgFare'])
print(data)

0      32.204208
1      32.204208
2      32.204208
3      32.204208
4      32.204208
         ...    
886    32.204208
887    32.204208
888    32.204208
889    32.204208
890    32.204208
Name: avgFare, Length: 891, dtype: float64
     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3    

In [30]:
data["Fare"] = data['Fare'].astype(int)

In [31]:
expensive_fares = data[data['Fare'] > 50]
print(expensive_fares['PassengerId'].count())

159


Finding young passengers

In [32]:
young_passengers = data[data['Age'] < 30]
print(young_passengers['PassengerId'].count())

561


In [33]:
data['Pclass'] = pd.Categorical(data['Pclass'])
data.head()

PassengerId  Survived Pclass  \
0            1         0      3   
1            2         1      1   
2            3         1      3   
3            4         1      1   
4            5         0      3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket  Fare Embarked    avgFare  
0      0         A/5 21171     7        S  32.204208  
1      0          PC 17599    71        C  32.204208  
2      0  STON/O2. 3101282     7        S  32.204208  
3      0            113803    53        S  32.204208  
4      0            373450     8        S  32.204208