In [2]:
import numpy as np
import pandas as pd

## Array Operations


In [11]:
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))
print(arr1)
print(arr2)

[[8 2 5]
 [8 4 6]
 [5 4 2]]
[[4 8 5]
 [2 8 6]
 [3 8 5]]


### Addition

In [12]:
print(arr1+arr2)
print(np.add(arr1,arr2))

[[12 10 10]
 [10 12 12]
 [ 8 12  7]]
[[12 10 10]
 [10 12 12]
 [ 8 12  7]]


### Subtraction

In [15]:
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ 4 -6  0]
 [ 6 -4  0]
 [ 2 -4 -3]]
[[ 4 -6  0]
 [ 6 -4  0]
 [ 2 -4 -3]]


### Multiplication & Dot Product

In [13]:
print(np.dot(arr1,arr2))
print(np.multiply(arr1,arr2))

[[ 51 120  77]
 [ 58 144  94]
 [ 34  88  59]]
[[32 16 25]
 [16 32 36]
 [15 32 10]]


### Division

In [14]:
print(np.mod(arr1,arr2))

[[0 2 0]
 [0 4 0]
 [2 4 2]]


## Statistical Analysis

In [26]:
array = np.array(np.random.randint(10,size=20))
print(array)

[2 1 8 6 8 1 7 9 6 1 0 6 3 5 3 8 6 6 0 8]


In [31]:
print(f'Median of array = {np.median(array)}')
print(f'Mean of array = {np.mean(array)}')
print(f'Standard deviation of array = {np.std(array)}')
print(f'Variance of array = {np.var(array)}')

Median of array = 6.0
Mean of array = 4.7
Standard deviation of array = 2.951270912674741
Variance of array = 8.709999999999999


## Matrix Manipulation

In [35]:
matrix = np.random.randint(low=1,high=30,size=(3,3))
print(matrix)

[[17 14 25]
 [20  4  8]
 [24 19 26]]


In [41]:
#matrix transposition
print(f'transposed matrix:\n {np.transpose(matrix)}')

#matrix dot product
print(f'dot product of the matrix: \n {np.dot(matrix,matrix)}')

#matrix determinant
print(f'Determinant of the matrix: \n{np.linalg.det(matrix)}')

transposed matrix:
 [[17 20 24]
 [14  4 19]
 [25  8 26]]
dot product of the matrix: 
 [[1169  769 1187]
 [ 612  448  740]
 [1412  906 1428]]
Determinant of the matrix: 
1691.9999999999995


## Data Manipulation and Transformation

In [45]:
data = pd.read_csv('titanic.csv')
print(data.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [51]:
data['avgFare'] = np.array(data['Fare']).mean()
print(data['avgFare'])
print(data)

0      32.204208
1      32.204208
2      32.204208
3      32.204208
4      32.204208
         ...    
886    32.204208
887    32.204208
888    32.204208
889    32.204208
890    32.204208
Name: avgFare, Length: 891, dtype: float64
     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0 

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [57]:
#labelling sex in new column
data['Gender'] = data['Sex'].apply(lambda x: 0 if x == 'male' else 1)
print(data['Gender'])

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Gender, Length: 891, dtype: int64


In [65]:
data["Fare"] = data['Fare'].astype(int)

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    int32  
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  avgFare      891 non-null    float64
 13  Gender       891 non-null    int64  
dtypes: float64(2), int32(1), int64(6), object(5)
memory usage: 94.1+ KB


In [67]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare       avgFare      Gender  
count  891.000000  891.000000  8.910000e+02  891.000000  
mean     0.381594   31.785634  3.220421e+01    0.352413  
std      0.806057   49.703730  7.109418e-15    0.477990  
min      0.000000    0.000000  3.220421e+01    0.000000  
25%      0.000000    7.000000  3.220421e+01    0.000000  
50%      0.000000   14.000000  3.220421e+01    0.000000  
75%      0.000000   31.000000  3.220421e+01    1.000000  
max      6.000000  512.000000  3.220421e+01    1.000000