### Name: Dheephiga A M 
### Worldline Temp ID: WDGET2024067
### Assessment - 2

### Numpy

In [1]:
import numpy as np
import pandas as pd

In [8]:
array1 = np.random.randint(1,101, size=(20))

array([88, 47, 31,  9, 82, 28, 22, 87, 78, 32, 69, 52, 58, 83, 69, 43, 41,
        3, 89, 88])

In [20]:
#reshaping the array
matrix1 = array1.reshape(4,5)
matrix1

array([[88, 47, 31,  9, 82],
       [28, 22, 87, 78, 32],
       [69, 52, 58, 83, 69],
       [43, 41,  3, 89, 88]])

In [17]:
#mean, median, standard deviation of the matrix
print(f'mean of matrix: {matrix1.mean()}')
print(f'median of matrix: {np.median(matrix1)}')
print(f'mean of matrix: {matrix1.std()}')

mean of matrix: 54.95
median of matrix: 55.0
mean of matrix: 27.34680054412216


In [19]:
#3x3 identity matrix
identityMatrix = np.eye(3)
identityMatrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#evenly spaced numbers
array3 = np.linspace(0,5,10)
array3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [35]:
#replacing values in an array
array4 = np.arange(0,10)
array4 = np.where(array4 % 2 == 0, -1, array4)
array4

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [44]:
#dot product of 2 matrices
mat1 = np.array([[1,2],
                [3,4],
                [5,6]])
# print(np.shape(mat1))
mat2 = np.array([[5,4,2],
                 [3,1,1]])
# print(np.shape(mat2))
print(f'Dot product of the matrices:\n{np.dot(mat1,mat2)}')

Dot product of the matrices:
[[11  6  4]
 [27 16 10]
 [43 26 16]]


In [46]:
#finding the indices of the min and max values in the array
max_value = np.max(array1)
max_index = np.argmax(array1)

min_value = np.min(array1)
min_index = np.argmin(array1)

print(f'Maximum value is {max_value}\nIndex is {max_index}')
print(f'Minimum value is {min_value}\nIndex is {min_index}')

Maximum value is 89
Index is 18
Minimum value is 3
Index is 17


In [51]:
#using filter in an array
array5 = np.arange(1,51)
array6 = array5[array5>30]
array6

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50])