### Name: Dheephiga A M 
### Worldline Temp ID: WDGET2024067
### Task 4

## Numpy

In [47]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [2]:
#2D 5x5 of random integers
array1 = np.random.randint(0,101,size=(5,5))

In [3]:
#reshaping the created array to 1D array
array2 = array1.flatten()
array2


array([38, 97, 91, 70, 46, 23, 65, 75, 53, 39, 49, 96, 98, 79, 20, 73,  4,
       53, 40, 13, 81, 48, 53, 33, 13])

In [4]:
#calculating the cumulatinve sum along the rows of the reshaped array
cumulativeSum = np.cumsum(array2)
print(cumulativeSum)

[  38  135  226  296  342  365  430  505  558  597  646  742  840  919
  939 1012 1016 1069 1109 1122 1203 1251 1304 1337 1350]


In [5]:
#a function that takes two arrays as input and returns the intersection
def intersection(a,b):
    return np.intersect1d(a,b)

n= int(input('Enter number of elements: '))
arr1 = list(map(int, 
    input("\nEnter the numbers : ").strip().split()))[:n]

n= int(input('Enter number of elements: '))
arr2 = list(map(int,input('\nEnter numbers: ').strip().split()))[:n]

print(intersection(np.array(arr1),np.array(arr2)))


[1]


In [6]:
#implementing softmax function
softmax = np.exp(array2)/sum(np.exp(array2))
print(softmax)


[5.82165787e-27 2.44580096e-01 6.06253445e-04 4.59695338e-13
 1.73541175e-23 1.78085865e-33 3.09740282e-15 6.82248374e-11
 1.90311007e-20 1.58249068e-26 3.48566768e-22 8.99759890e-02
 6.64837630e-01 3.72494991e-09 8.86637314e-35 9.23322769e-12
 9.97778850e-42 1.90311007e-20 4.30165566e-26 8.08508576e-38
 2.75238638e-08 1.28230548e-22 1.90311007e-20 3.92260221e-29
 8.08508576e-38]


In [7]:
#creating a matrix with random integers and replace negative integers with their abs square
array3 = np.random.randint(-20,20,size=(15))
print(array3)
arr3 = [x*x if x < 0 else x for x in array3]
print(arr3)

[  2 -19 -19 -19 -13 -17 -20 -17 -12 -18   1  18   7   5  -3]
[2, 361, 361, 361, 169, 289, 400, 289, 144, 324, 1, 18, 7, 5, 9]


In [8]:
array4 = np.random.randint(0,100,size=(6,6))
symmetricArray = (array4+array4.T)/2
print(symmetricArray)

eigenVal = np.linalg.eig(symmetricArray)
print(eigenVal)


[[81.  51.  82.  18.5 42.5 37.5]
 [51.  13.  62.  64.  54.  37.5]
 [82.  62.  22.  70.5 42.5 46. ]
 [18.5 64.  70.5 52.  13.  90.5]
 [42.5 54.  42.5 13.  56.  21. ]
 [37.5 37.5 46.  90.5 21.  28. ]]
EigResult(eigenvalues=array([290.20912198,  78.57584339,  29.52546038, -71.35724681,
       -24.44962975, -50.50354918]), eigenvectors=array([[ 0.4466229 ,  0.52996186, -0.59540701,  0.31225748,  0.19095366,
        -0.17660937],
       [ 0.39784875,  0.02377357,  0.21477892, -0.2584696 , -0.52579164,
        -0.67212932],
       [ 0.45801213,  0.05922754, -0.14748076, -0.44995286, -0.34265342,
         0.66715626],
       [ 0.43761311, -0.59135804,  0.05639299,  0.64654363, -0.14899651,
         0.12406305],
       [ 0.31400708,  0.44516705,  0.75695697,  0.1612696 ,  0.27817024,
         0.16387629],
       [ 0.37731098, -0.40888789, -0.03802514, -0.43497657,  0.68563098,
        -0.17235648]]))


In [9]:
#calculating moving average of 1D array
def moving_average(arr, window_size):
    if window_size <= 0 or window_size > len(arr):
        raise ValueError("Window size must be a positive integer less than or equal to the length of the array.")
    
    moving_averages = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
    return moving_averages


array5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window = 3
result = moving_average(array5, window)
print("Moving averages:", result)


Moving averages: [2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
#checkerboard pattern using zeros and ones
board = np.zeros((8, 8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
#pearson correlation coefficient of two random arrays of same length

array5 = np.random.randint(1,20,size=(3,3))
array6 = np.random.randint(1,30,size=(3,3))

print(np.corrcoef(array5,array6))

[[ 1.          0.8660254   0.8660254  -0.32732684 -0.39735971 -0.07051994]
 [ 0.8660254   1.          1.          0.18898224  0.11470787 -0.55982725]
 [ 0.8660254   1.          1.          0.18898224  0.11470787 -0.55982725]
 [-0.32732684  0.18898224  0.18898224  1.          0.99717646 -0.91947563]
 [-0.39735971  0.11470787  0.11470787  0.99717646  1.         -0.88735651]
 [-0.07051994 -0.55982725 -0.55982725 -0.91947563 -0.88735651  1.        ]]


In [12]:
#Generate a random 3D array and compute the sum along each axis

array3d = np.random.randint(1,100, size=(2,3,4))

print(f'axis-1: {np.sum(array3d,axis=0)}\n\naxis-2:{np.sum(array3d,axis=1)}\n\n axis-3:{np.sum(array3d,axis=2)}\n' )

axis-1: [[ 33  22 109  91]
 [ 92 126 173 107]
 [147  34 178  55]]

axis-2:[[ 92  84 265 145]
 [180  98 195 108]]

 axis-3:[[120 258 208]
 [135 240 206]]



## Pandas

In [13]:
#Read multiple CSV files from a directory into a single pandas DataFrame and concatenate them.

df = pd.concat(map(pd.read_csv, ['train.csv', 'test.csv']))

In [14]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       1.0       1   
2            3       1.0       3   
3            4       1.0       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [15]:
specificAge = df[(df['Age']>= 25) & (df['Age']<=35)]
print(specificAge.head())
print(specificAge.count())

    PassengerId  Survived  Pclass  \
2             3       1.0       3   
3             4       1.0       1   
4             5       0.0       3   
8             9       1.0       3   
18           19       0.0       3   

                                                 Name     Sex   Age  SibSp  \
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   

    Parch            Ticket     Fare Cabin Embarked  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
8       2            347742  11.1333   NaN        S  
18      0            345763  18.0000  

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64  
 3   Name         1309 non-null   object 
 4   Sex          1309 non-null   object 
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64  
 7   Parch        1309 non-null   int64  
 8   Ticket       1309 non-null   object 
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object 
 11  Embarked     1307 non-null   object 
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB


In [17]:
#Group the DataFrame by the 'City' column and calculate various statistics (mean, median, max, min) for the 'Salary' column within each group
df_salary = pd.read_csv('data.csv')
df_salary.head()


Name  Age         City  Salary  Years of Experience
0    A   23  Santa Clara   70000                    2
1    B   42  Santa Clara   50000                    5
2    C   33       Boston   60000                    7
3    D   52  Los Angeles   70000                    8
4    E   25       Boston   80000                    9

In [18]:
salaryGroupByCity = df_salary.groupby('City')

In [19]:
print(f'Mean of the salaries, grouped by city\n{salaryGroupByCity['Salary'].mean()}')

Mean of the salaries, grouped by city
City
Boston         66666.666667
Brooklyn       60000.000000
Chicago        50000.000000
Los Angeles    70000.000000
Ohio           70000.000000
Santa Clara    60000.000000
Name: Salary, dtype: float64


In [20]:
print(f'Median of the salaries, grouped by city\n{salaryGroupByCity['Salary'].median()}')

Median of the salaries, grouped by city
City
Boston         60000.0
Brooklyn       60000.0
Chicago        50000.0
Los Angeles    70000.0
Ohio           70000.0
Santa Clara    60000.0
Name: Salary, dtype: float64


In [21]:
print(f'Maximum of the salaries, grouped by city\n{salaryGroupByCity['Salary'].max()}')

Maximum of the salaries, grouped by city
City
Boston         80000
Brooklyn       70000
Chicago        50000
Los Angeles    70000
Ohio           70000
Santa Clara    70000
Name: Salary, dtype: int64


In [22]:
print(f'Minimum of the salaries, grouped by city\n{salaryGroupByCity['Salary'].min()}')

Minimum of the salaries, grouped by city
City
Boston         60000
Brooklyn       50000
Chicago        50000
Los Angeles    70000
Ohio           70000
Santa Clara    50000
Name: Salary, dtype: int64


Outer join between two DataFrames based on a common column, df and df_salary have the column Age in common


In [23]:
#outer join between two DataFrames based on a common column
age_merged = pd.merge(df , df_salary, on='Age', how='outer')

C:\Users\Anitha\AppData\Local\Temp\ipykernel_1844\3034972450.py:2: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  age_merged = pd.merge(df , df_salary, on='Age', how='outer')


In [24]:
df_salary.head()

Name  Age         City  Salary  Years of Experience
0    A   23  Santa Clara   70000                    2
1    B   42  Santa Clara   50000                    5
2    C   33       Boston   60000                    7
3    D   52  Los Angeles   70000                    8
4    E   25       Boston   80000                    9

In [25]:
df['Age'] = df['Age'].fillna(0)
df['Age'].astype(int)


0      22
1      38
2      26
3      35
4      35
       ..
413     0
414    39
415    38
416     0
417     0
Name: Age, Length: 1309, dtype: int32

In [26]:
#outer join between two DataFrames based on a common column
age_merged = pd.merge(df , df_salary, on='Age', how='outer')
age_merged.head()

C:\Users\Anitha\AppData\Local\Temp\ipykernel_1844\2795978508.py:2: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  age_merged = pd.merge(df , df_salary, on='Age', how='outer')


PassengerId  Survived  Pclass                         Name_x     Sex  Age  \
0            6       0.0       3               Moran, Mr. James    male  0.0   
1           18       1.0       2   Williams, Mr. Charles Eugene    male  0.0   
2           20       1.0       3        Masselmani, Mrs. Fatima  female  0.0   
3           27       0.0       3        Emir, Mr. Farred Chehab    male  0.0   
4           29       1.0       3  O'Dwyer, Miss. Ellen "Nellie"  female  0.0   

   SibSp  Parch  Ticket     Fare Cabin Embarked Name_y City  Salary  \
0      0      0  330877   8.4583   NaN        Q    NaN  NaN     NaN   
1      0      0  244373  13.0000   NaN        S    NaN  NaN     NaN   
2      0      0    2649   7.2250   NaN        C    NaN  NaN     NaN   
3      0      0    2631   7.2250   NaN        C    NaN  NaN     NaN   
4      0      0  330959   7.8792   NaN        Q    NaN  NaN     NaN   

   Years of Experience  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN

In [27]:
df_time = pd.read_csv('flowdata.csv')
df_time.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11697 entries, 0 to 11696
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Time      11697 non-null  object 
 1   L06_347   11696 non-null  float64
 2   LS06_347  11425 non-null  float64
 3   LS06_348  10689 non-null  float64
dtypes: float64(3), object(1)
memory usage: 365.7+ KB


In [28]:
df_time['Time'] = df_time['Time'].astype(str)

In [29]:
print(df_time['Time'].dtype)

object


In [30]:
#Implement a function that converts a DataFrame column containing dates in string format to a datetime object.

def convert_to_datetime(df, column_name):    
    df[column_name] = pd.to_datetime(df[column_name])
    return df
df_time = convert_to_datetime(df_time, 'Time')
df_time.head()

Time   L06_347  LS06_347  LS06_348
0 2009-01-01 00:00:00  0.137417  0.097500  0.016833
1 2009-01-01 03:00:00  0.131250  0.088833  0.016417
2 2009-01-01 06:00:00  0.113500  0.091250  0.016750
3 2009-01-01 09:00:00  0.135750  0.091500  0.016250
4 2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [31]:
df.rename(columns={'Age': 'years Old'}, inplace=True)

In [32]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'years Old',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [33]:
mergeDataframe = pd.merge(df,df_salary,left_on='years Old',right_on='Age')

C:\Users\Anitha\AppData\Local\Temp\ipykernel_1844\1224262529.py:1: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  mergeDataframe = pd.merge(df,df_salary,left_on='years Old',right_on='Age')


In [34]:
mergeDataframe.head()

PassengerId  Survived  Pclass  \
0            2       1.0       1   
1            4       1.0       1   
2            5       0.0       3   
3           21       0.0       2   
4           26       1.0       3   

                                              Name_x     Sex  years Old  \
0  Cumings, Mrs. John Bradley (Florence Briggs Th...  female       38.0   
1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       35.0   
2                           Allen, Mr. William Henry    male       35.0   
3                               Fynney, Mr. Joseph J    male       35.0   
4  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female       38.0   

   SibSp  Parch    Ticket     Fare Cabin Embarked Name_y  Age      City  \
0      1      0  PC 17599  71.2833   C85        C      J   38  Brooklyn   
1      1      0    113803  53.1000  C123        S      G   35    Boston   
2      0      0    373450   8.0500   NaN        S      G   35    Boston   
3      0      0    239865  26.0000   NaN        S      G   35    Boston   
4      1      5    347077  31.3875   NaN        S      J   38  Brooklyn   

   Salary  Years of Experience  
0   50000                    1  
1   60000                   10  
2   60000                   10  
3   60000                   10  
4   50000                    1

In [35]:
df_store = pd.read_csv('Global_Superstore(CSV).csv')
df_store.head()

Row ID                  Order ID  Order Date   Ship Date     Ship Mode  \
0   40098  CA-2014-AB10015140-41954  11/11/2014  11/13/2014   First Class   
1   26341    IN-2014-JR162107-41675    2/5/2014    2/7/2014  Second Class   
2   25330    IN-2014-CR127307-41929  10/17/2014  10/18/2014   First Class   
3   13524   ES-2014-KM1637548-41667   1/28/2014   1/30/2014   First Class   
4   47221   SG-2014-RH9495111-41948   11/5/2014   11/6/2014      Same Day   

    Customer ID     Customer Name      Segment  Postal Code           City  \
0  AB-100151402     Aaron Bergman     Consumer      73120.0  Oklahoma City   
1     JR-162107     Justin Ritter    Corporate          NaN     Wollongong   
2     CR-127307      Craig Reiter     Consumer          NaN       Brisbane   
3    KM-1637548  Katherine Murray  Home Office          NaN         Berlin   
4    RH-9495111       Rick Hansen     Consumer          NaN          Dakar   

   ...   Product ID    Category Sub-Category  \
0  ...  TEC-PH-5816  Technology       Phones   
1  ...  FUR-CH-5379   Furniture       Chairs   
2  ...  TEC-PH-5356  Technology       Phones   
3  ...  TEC-PH-5267  Technology       Phones   
4  ...  TEC-CO-6011  Technology      Copiers   

                                Product Name    Sales Quantity Discount  \
0                           Samsung Convoy 3   221.98        2      0.0   
1  Novimex Executive Leather Armchair, Black  3709.40        9      0.1   
2          Nokia Smart Phone, with Caller ID  5175.17        9      0.1   
3             Motorola Smart Phone, Cordless  2892.51        5      0.1   
4             Sharp Wireless Fax, High-Speed  2832.96        8      0.0   

   Profit  Shipping Cost  Order Priority  
0   62.15          40.77            High  
1 -288.77         923.63        Critical  
2  919.97         915.49          Medium  
3  -96.54         910.16          Medium  
4  311.52         903.04        Critical  

[5 rows x 24 columns]

In [36]:
#Calculate the cumulative sum of the 'Sales' column in the DataFrame while resetting the sum whenever a new 'Region' appears.
df_store['Cumulative_Sales'] = df_store.groupby('Region')['Sales'].cumsum()
print(df_store['Cumulative_Sales'])

0         221.98
1        3709.40
2        8884.57
3        2892.51
4        2832.96
         ...    
995    193590.60
996     16729.95
997    220809.08
998     64550.54
999    147337.60
Name: Cumulative_Sales, Length: 1000, dtype: float64


In [37]:
df_store.head()

Row ID                  Order ID  Order Date   Ship Date     Ship Mode  \
0   40098  CA-2014-AB10015140-41954  11/11/2014  11/13/2014   First Class   
1   26341    IN-2014-JR162107-41675    2/5/2014    2/7/2014  Second Class   
2   25330    IN-2014-CR127307-41929  10/17/2014  10/18/2014   First Class   
3   13524   ES-2014-KM1637548-41667   1/28/2014   1/30/2014   First Class   
4   47221   SG-2014-RH9495111-41948   11/5/2014   11/6/2014      Same Day   

    Customer ID     Customer Name      Segment  Postal Code           City  \
0  AB-100151402     Aaron Bergman     Consumer      73120.0  Oklahoma City   
1     JR-162107     Justin Ritter    Corporate          NaN     Wollongong   
2     CR-127307      Craig Reiter     Consumer          NaN       Brisbane   
3    KM-1637548  Katherine Murray  Home Office          NaN         Berlin   
4    RH-9495111       Rick Hansen     Consumer          NaN          Dakar   

   ...    Category Sub-Category                               Product Name  \
0  ...  Technology       Phones                           Samsung Convoy 3   
1  ...   Furniture       Chairs  Novimex Executive Leather Armchair, Black   
2  ...  Technology       Phones          Nokia Smart Phone, with Caller ID   
3  ...  Technology       Phones             Motorola Smart Phone, Cordless   
4  ...  Technology      Copiers             Sharp Wireless Fax, High-Speed   

     Sales Quantity Discount  Profit Shipping Cost  Order Priority  \
0   221.98        2      0.0   62.15         40.77            High   
1  3709.40        9      0.1 -288.77        923.63        Critical   
2  5175.17        9      0.1  919.97        915.49          Medium   
3  2892.51        5      0.1  -96.54        910.16          Medium   
4  2832.96        8      0.0  311.52        903.04        Critical   

   Cumulative_Sales  
0            221.98  
1           3709.40  
2           8884.57  
3           2892.51  
4           2832.96  

[5 rows x 25 columns]

In [38]:
df_time.head()

Time   L06_347  LS06_347  LS06_348
0 2009-01-01 00:00:00  0.137417  0.097500  0.016833
1 2009-01-01 03:00:00  0.131250  0.088833  0.016417
2 2009-01-01 06:00:00  0.113500  0.091250  0.016750
3 2009-01-01 09:00:00  0.135750  0.091500  0.016250
4 2009-01-01 12:00:00  0.140917  0.096167  0.017000

In [39]:
df_time.reset_index()

index                Time   L06_347  LS06_347  LS06_348
0          0 2009-01-01 00:00:00  0.137417  0.097500  0.016833
1          1 2009-01-01 03:00:00  0.131250  0.088833  0.016417
2          2 2009-01-01 06:00:00  0.113500  0.091250  0.016750
3          3 2009-01-01 09:00:00  0.135750  0.091500  0.016250
4          4 2009-01-01 12:00:00  0.140917  0.096167  0.017000
...      ...                 ...       ...       ...       ...
11692  11692 2013-01-01 12:00:00  1.710000  1.710000  0.129583
11693  11693 2013-01-01 15:00:00  1.420000  1.420000  0.096333
11694  11694 2013-01-01 18:00:00  1.178583  1.178583  0.083083
11695  11695 2013-01-01 21:00:00  0.898250  0.898250  0.077167
11696  11696 2013-01-02 00:00:00  0.860000  0.860000  0.075000

[11697 rows x 5 columns]

In [40]:
df_time['Time'] = pd.to_datetime(df_time['Time'])

In [41]:
df_time.set_index('Time', inplace=True)

In [42]:
#Resample time series data in a DataFrame into weekly intervals and calculate the mean for each week.
weekly_mean = df_time.resample('W').mean()
print(weekly_mean)

             L06_347  LS06_347  LS06_348
Time                                    
2009-01-04  0.125729  0.094078  0.016615
2009-01-11  0.105039  0.078515  0.014790
2009-01-18  0.334137  0.345030  0.035988
2009-01-25  1.550421  1.693226  0.116491
2009-02-01  0.260927  0.228435  0.028437
...              ...       ...       ...
2012-12-09  0.526607  0.526607  0.075658
2012-12-16  0.359560  0.359560  0.050853
2012-12-23  1.241876  1.241876  0.115208
2012-12-30  1.389836  1.389836  0.132568
2013-01-06  1.218309  1.218309  0.109642

[210 rows x 3 columns]


In [43]:
df_time.rename(columns={'L06_347':'column1','LS06_347':'column2','LS06_348':'column3'},inplace=True)

In [44]:
#Use the apply function to perform a custom operation on each element of a DataFrame column.
def round_ceil(x):
    return np.ceil(x)

def round_floor(x):
    return np.floor(x)

def round_int(x):
    if not np.isnan(x):
        return int(x)
    else:
        return np.nan

df_time['modifiedCol1'] = df_time['column1'].apply(round_ceil)
df_time['modifiedCol2'] = df_time['column2'].apply(round_floor)
df_time['modifiedCol3'] = df_time['column3'].apply(round_int)

In [45]:
df_time.head()

column1   column2   column3  modifiedCol1  modifiedCol2  \
Time                                                                            
2009-01-01 00:00:00  0.137417  0.097500  0.016833           1.0           0.0   
2009-01-01 03:00:00  0.131250  0.088833  0.016417           1.0           0.0   
2009-01-01 06:00:00  0.113500  0.091250  0.016750           1.0           0.0   
2009-01-01 09:00:00  0.135750  0.091500  0.016250           1.0           0.0   
2009-01-01 12:00:00  0.140917  0.096167  0.017000           1.0           0.0   

                     modifiedCol3  
Time                               
2009-01-01 00:00:00           0.0  
2009-01-01 03:00:00           0.0  
2009-01-01 06:00:00           0.0  
2009-01-01 09:00:00           0.0  
2009-01-01 12:00:00           0.0

In [46]:
#Implement a function that detects and removes any duplicate rows in a DataFrame
def remove_duplicates(df):
    df_updated = df.drop_duplicates()
    return df_updated

remove_duplicates(df)

PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              2       1.0       1   
2              3       1.0       3   
3              4       1.0       1   
4              5       0.0       3   
..           ...       ...     ...   
413         1305       NaN       3   
414         1306       NaN       1   
415         1307       NaN       3   
416         1308       NaN       3   
417         1309       NaN       3   

                                                  Name     Sex  years Old  \
0                              Braund, Mr. Owen Harris    male       22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female       38.0   
2                               Heikkinen, Miss. Laina  female       26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female       35.0   
4                             Allen, Mr. William Henry    male       35.0   
..                                                 ...     ...        ...   
413                                 Spector, Mr. Woolf    male        0.0   
414                       Oliva y Ocana, Dona. Fermina  female       39.0   
415                       Saether, Mr. Simon Sivertsen    male       38.5   
416                                Ware, Mr. Frederick    male        0.0   
417                           Peter, Master. Michael J    male        0.0   

     SibSp  Parch              Ticket      Fare Cabin Embarked  
0        1      0           A/5 21171    7.2500   NaN        S  
1        1      0            PC 17599   71.2833   C85        C  
2        0      0    STON/O2. 3101282    7.9250   NaN        S  
3        1      0              113803   53.1000  C123        S  
4        0      0              373450    8.0500   NaN        S  
..     ...    ...                 ...       ...   ...      ...  
413      0      0           A.5. 3236    8.0500   NaN        S  
414      0      0            PC 17758  108.9000  C105        C  
415      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0      0              359309    8.0500   NaN        S  
417      1      1                2668   22.3583   NaN        C  

[1309 rows x 12 columns]