### Name: Dheephiga A M


### Worldline Temp ID: WDGET2024067


### Assessment - 2

### Task -1

In [2]:
import numpy as np
import pandas as pd

creating a numpy array of 10 random integers between 1 to 100

In [12]:
array = np.random.randint(low=1,high=101,size=(10,))
print(array)

[10 91 29 94 63 22 63  2  1 56]


Reshaping the array to 2x5 matrix

In [52]:
rearray1= array.reshape(2,5)

assigning a repeated value to perform removing duplicates as next step

In [39]:
rearray1[1,0] = 10
print(rearray1)

[[10 91 29 94 63]
 [10 63  2  1 56]]


Removing duplicates from the matrix

In [84]:
df = pd.DataFrame(rearray1)
unique_elements = pd.DataFrame(df.stack().unique())
df = unique_elements
print(unique_elements)

    0
0  10
1  91
2  29
3  94
4  63
5   2
6   1
7  56


Arranging in ascending and descending order

In [85]:
df.sort_values(by=0,ascending=True)


0
6   1
5   2
0  10
2  29
7  56
4  63
1  91
3  94

In [86]:
df.sort_values(by=0,ascending = False)

0
3  94
1  91
4  63
7  56
2  29
0  10
5   2
6   1

## Task -2

Creating a numpy array containing 10 float numbers from 1 to 50

In [35]:
array2 = np.random.rand(10) * 49 +1
print(array2)

[28.97428117 40.03167239  6.29880515  1.06850485 34.87333199 13.45359714
 42.76996046 16.94432576 28.35985222 35.23776553]


reshaping it to 2x5 matrix

In [37]:
rearray2= array2.reshape(2,5)
print(rearray2)

[[28.97428117 40.03167239  6.29880515  1.06850485 34.87333199]
 [13.45359714 42.76996046 16.94432576 28.35985222 35.23776553]]


Calculating max, min,sum, mean and standard deviation in both axes

In [90]:
print(f'Maximum values {rearray2.max(axis=1)}')
print(f'Minimum values {rearray2.min(axis=1)}')
print(f'Mean {rearray2.mean(axis=1)}')
print(f'Standard Deviation {rearray2.std(axis=1)}')
print(f'Sum {rearray2.sum(axis=1)}')

Maximum values [40.03167239 42.76996046]
Minimum values [ 1.06850485 13.45359714]
Mean [22.24931911 27.35310022]
Standard Deviation [15.64511868 10.9763368 ]
Sum [111.24659554 136.76550111]


## Task - 3

Creating a fruits dataframe from dictionary

In [105]:
fruits = {'apple':4,'orange':9,'cherry':7,'pine':12}
fruits = pd.DataFrame.from_dict(fruits,orient='index', columns=['quantity'])
print(fruits)

        quantity
apple          4
orange         9
cherry         7
pine          12


creating a new column price per unit and assigning random values to it

In [100]:
fruits['price/unit'] = np.random.uniform(low=15,high=67,size=len(fruits))
print(fruits)

        quantity  price/unit
apple          4   62.115721
orange         9   28.700729
cherry         7   23.280650
pine          12   40.983930


In [103]:
fruits['total_cost'] = fruits['quantity'] * fruits['price/unit']
print(fruits)

        quantity  price/unit  total_cost
apple          4   62.115721  248.462883
orange         9   28.700729  258.306559
cherry         7   23.280650  162.964547
pine          12   40.983930  491.807155


In [104]:
sorted_fruits= fruits.sort_values(by='total_cost', ascending=False)
print(sorted_fruits)

        quantity  price/unit  total_cost
pine          12   40.983930  491.807155
orange         9   28.700729  258.306559
apple          4   62.115721  248.462883
cherry         7   23.280650  162.964547


## Task - 4

Creating a dataframe of colors and frequencies

In [108]:
colours = {'yellow': 8, 'purple': 5, 'teal': 6, 'magenta': 3}
colors= pd.DataFrame.from_dict(colours, orient='index', columns=['freq'])
print(colors)

         freq
yellow      8
purple      5
teal        6
magenta     3


creating a column to add hexcodes of the colors

In [112]:
colors['hex_Values'] = ['#po78561','#7848ed','#25588fe','#uh71369']
print(colors)

         freq hex_Values
yellow      8   #po78561
purple      5    #7848ed
teal        6   #25588fe
magenta     3   #uh71369


Sorting based on frequency in descending

In [114]:
sorted_Colors = colors.sort_values(by='freq',ascending=False)
print(sorted_Colors)

         freq hex_Values
yellow      8   #po78561
teal        6   #25588fe
purple      5    #7848ed
magenta     3   #uh71369


Calculating cumulative sum of frequencies

In [115]:
cumulative_freq = colors['freq'].cumsum()
print(cumulative_freq)

yellow      8
purple     13
teal       19
magenta    22
Name: freq, dtype: int64
