In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,2,4,5,])
print(arr)
print(np.ndim(arr))
arr2 = np.array([[1,11,1,1,1,1,1,]])
print(np.ndim(arr2))

[1 2 2 4 5]
1
2


In [7]:
marks = np.array([[90,90,87],
                  [90,99,97],
                  [80,88,98],])
print(np.ndim(marks))

2


In [8]:
reshp = arr.reshape(5,1)
print(reshp)
print(np.ndim(reshp))

[[1]
 [2]
 [2]
 [4]
 [5]]
2


In [9]:
#reshaping multi to single
reshaped = marks.flatten()
print(np.ndim(reshaped))
print(reshaped)


1
[90 90 87 90 99 97 80 88 98]


new course
add marks
add 2 more studetns

In [10]:
subjs = np.array([[85, 82],
                [79, 91],
                [90, 88]])
marks = np.hstack((marks, subjs))

new_students = np.array([[85, 82, 88,99,100],
                        [79, 91, 83,89,99]])
marks = np.vstack(marks,new_students)
average_marks = np.mean(marks, axis=0)
marks = np.vstack([marks, average_marks])

TypeError: vstack() takes 1 positional argument but 2 were given

In [ ]:
import numpy as np

# Sample array of values


# Printing values using row and column indices
for i in range(len(row_indices)):
    row_idx = row_indices[i]
    col_idx = col_indices[i]
    print(f"Value at ({row_idx}, {col_idx}): {values[row_idx, col_idx]}")
values = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Sample array of row and column indices
row_indices = np.array([ 1, 2])
col_indices = np.array([2])

each student's max mark print
what std marks are greater than 70


In [ ]:
print(marks)

[[90 90 87]
 [90 99 97]
 [80 88 98]]


In [ ]:
import numpy as np


marks = np.array([[78, 89, 67],
                  [56, 89, 90],
                  [90, 56, 90]])


subjs = np.array([[85, 82],
                  [79, 91],
                  [90, 88]])

marks = np.hstack((marks, subjs))


new_students = np.array([[85, 82, 88, 99, 100],
                         [79, 91, 83, 89, 99]])


marks = np.vstack((marks, new_students))


average_marks = np.mean(marks, axis=0)

marks = np.vstack([marks.astype(int), average_marks.astype(int)])
print("Updated marks array:")
print(marks)


Updated marks array:
[[ 78  89  67  85  82]
 [ 56  89  90  79  91]
 [ 90  56  90  90  88]
 [ 85  82  88  99 100]
 [ 79  91  83  89  99]
 [ 77  81  83  88  92]]


In [ ]:
max_marks_per_student = np.max(marks, axis=1)

print("Maximum marks for each student:")
print(max_marks_per_student)

Maximum marks for each student:
[ 89  91  90 100  99  92]


In [12]:
import numpy as np

# Creating a non-singular 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 10]])

print("Original Matrix:")
print(matrix)

# Calculating the inverse of the matrix
try:
    inv_matrix = np.linalg.inv(matrix)
    print("\nInverse Matrix:")
    print(inv_matrix)
except np.linalg.LinAlgError as e:
    print("Error:", e)


Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Inverse Matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [17]:
result1 = np.matmul(matrix,inv_matrix)
result2 = np.matmul(inv_matrix,matrix)
print(result1)
print('\n')
print(result2)

[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]


[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 1.33226763e-15  1.00000000e+00  8.88178420e-16]
 [-7.77156117e-16  0.00000000e+00  1.00000000e+00]]


In [24]:
eignfull = np.full(fill_value=4,shape=(3,3))
print(np.linalg.eig(eignfull))

eigndiag = np.eye(3,3)
egdval, egdvec = np.linalg.eig(eigndiag)
print(egdval,egdvec)

EigResult(eigenvalues=array([-8.8817842e-16,  1.2000000e+01,  0.0000000e+00]), eigenvectors=array([[-0.81649658,  0.57735027,  0.        ],
       [ 0.40824829,  0.57735027, -0.70710678],
       [ 0.40824829,  0.57735027,  0.70710678]]))
[1. 1. 1.] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
svdmatrix = np.array([[1,3,5],[2,3,2],[2,3,4]])
u,s,v = np.linalg.svd(svdmatrix)
print(f'u: {u} s: {s}\nv: {v}\n')

p = np.dot(u,s)
q = np.dot(p,v)
print(q)

u: [[-0.65952021  0.61101001 -0.43783543]
 [-0.43945834 -0.7859739  -0.43488089]
 [-0.6098438  -0.0944023   0.78687912]] s: [8.81237507 1.78802845 0.38078852]
v: [[-0.3129831  -0.581735   -0.75075027]
 [-0.64302243 -0.45194951  0.61827485]
 [ 0.69897334 -0.67625884  0.2326161 ]]

[ 1.36470139  8.84853741 -0.91704736]
