In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,2,4,5,])
print(arr)
print(np.ndim(arr))
arr2 = np.array([[1,11,1,1,1,1,1,]])
print(np.ndim(arr2))

[1 2 2 4 5]
1
2


In [14]:
marks = np.array([[90,90,87],
                  [90,99,97],
                  [80,88,98],])
print(np.ndim(marks))

2


In [26]:
reshp = arr.reshape(5,1)
print(reshp)
print(np.ndim(reshp))

[[1]
 [2]
 [2]
 [4]
 [5]]
2


In [22]:
#reshaping multi to single
reshaped = marks.flatten()
print(np.ndim(reshaped))
print(reshaped)


1
[90 90 87 90 99 97 80 88 98]


new course
add marks
add 2 more studetns

In [ ]:
subjs = np.array([[85, 82],
                [79, 91],
                [90, 88]])
marks = np.hstack((marks, subjs))

new_students = np.array([[85, 82, 88,99,100],
                        [79, 91, 83,89,99]])
marks = np.vstack(marks,new_students)
average_marks = np.mean(marks, axis=0)
marks = np.vstack([marks, average_marks])