In [6]:
import numpy as np

In [2]:
array = [[3,2],[3,5],[3,6]] #list
print(array)

[[3, 2], [3, 5], [3, 6]]


In [17]:
list1= [int(item) for item in input("Enter numbers: \
                 : ").split(',')]
array = np.array(list1)
print(array)
print(array.ndim)

[1 2 3 4 5]
1


create 3x3, use itemsize, dtype, shape, ndim

In [16]:
three = np.array([[1,2,3],[1,3,4],[3,4,5]])
print(three.ndim) #dimension
print(three.dtype) #datatype
print(three.itemsize) #size of single element
print(three.shape) # n x n
print(three.nbytes) #total size
print(three.size) #no. of elements


2
int32
4
(3, 3)
36
9


In [18]:
def check_array(in_array):
    print("Shape: ",in_array.shape)
    print("Data type: ",in_array.dtype)
    print("Item size: ",in_array.itemsize)

list1= [int(item) for item in input("Enter numbers: ").split(',')]
array = np.array(list1)
check_array(array)

Shape:  (8,)
Data type:  int32
Item size:  4


In [19]:
three

array([[1, 2, 3],
       [1, 3, 4],
       [3, 4, 5]])

In [22]:
def change(c_row,c_column,c_value,in_array):
    if c_row <= in_array.shape[0] and c_column <= in_array.shape[1]:
        in_array[c_row,c_column]= c_value
        print(in_array)
    else:
        print("Invalid")
three = np.array([[1,2,3],[1,3,4],[3,4,5]])

change(1,0,4,three)

[[1 2 3]
 [4 3 4]
 [3 4 5]]


In [25]:
np.full([1,3,4],9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [26]:
np.full_like(three,7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [31]:
np.zeros_like(three)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.random.rand(3,5)

array([[0.06254734, 0.02454672, 0.11093179, 0.20734194, 0.10472424],
       [0.63404817, 0.34869663, 0.7268903 , 0.46037188, 0.69171688],
       [0.36251589, 0.94237448, 0.4569828 , 0.43007115, 0.5987523 ]])

In [38]:
np.random.randint(1,3,size=(3,6))

array([[1, 1, 2, 2, 2, 2],
       [1, 1, 2, 1, 2, 2],
       [1, 1, 2, 1, 1, 2]])

With user input, create a matrix and perform addition with a existing matrix and print it

In [44]:
def np_functions(choice):
    print(np.full_like(three,choice) + three)

np_functions(int(input()))

[[ 6  7  8]
 [ 9  8  9]
 [ 8  9 10]]


eye vs identity

In [47]:
#Creates an array of 4 x 4 with the main diagonal of 1

arr1 = np.eye(4)
print(arr1)

print("\n")

#or you can change the diagonal position

arr2 = np.eye(4, k=2)  # or try with another number like k= -2
print(arr2)

print("\n")

#but you can't change the diagonal in identity

arr3 = np.identity(4)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
three.repeat(3,(3,2))

TypeError: 'tuple' object cannot be interpreted as an integer

create a random number matrix with ub lb from user, print it

In [58]:
def random_matrix(up,low,dim):
    print(np.random.randint(low,up+1,size=(dim,dim)))

u = int(input("Upper bound: "))
l = int(input("Lower bound: "))
n = int(input("Dimension: "))
random_matrix(u,l,n)


ValueError: low >= high